language: python

env:
 global:
  - HELM_URL=https://storage.googleapis.com/kubernetes-helm
  - HELM_TGZ=helm-v2.4.1-linux-amd64.tar.gz

install:
  # Installing Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only

before_script:
  # Decrypt key
  - >
    openssl aes-256-cbc
    -K $encrypted_1f5633e62941_key
    -iv $encrypted_1f5633e62941_iv
    -in .ssh-keys/travis.enc
    -out .ssh-keys/travis
    -d

  # Add the keypair to the agent
  - chmod 600 .ssh-keys/travis
  - eval "$(ssh-agent -s)"
  - ssh-add .ssh-keys/travis

script:
  - ls
  - pwd
  # Current dir and temporary dir for storing new packaged charts and index files
  - REPO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  - BUILD_DIR=$(mktemp -d)

  # Useful URLs
  - REPO_URL=`git config remote.origin.url`
  - SSH_REPO=${REPO_URL/https:\/\/github.com\//git@github.com:}
  - SHA=`git rev-parse --verify HEAD`

  # Push temporary directory to the stack
  - pushd $BUILD_DIR

  # Iterate over all charts are package them
  - for dir in `ls charts/`; do
    helm dep update charts/$dir;
    helm package charts/$dir; 
    done

  # Indexing of charts
  - if [ -f index.yaml ]; then
    helm repo index --url ${REPO_URL} --merge index.yaml .;
    else
    helm repo index --url ${REPO_URL} .;
    fi
  # Pop temporary directory from the stack
  - popd