language: python

before_script:
  # Decrypt key
  - >
    openssl aes-256-cbc
    -K $encrypted_1f5633e62941_key
    -iv $encrypted_1f5633e62941_iv
    -in .ssh-keys/travis.enc
    -out .ssh-keys/travis
    -d

  # Add the keypair to the agent
  - chmod 600 .ssh-keys/travis
  - eval "$(ssh-agent -s)"
  - ssh-add .ssh-keys/travis

script: true
