apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    app: {{ .Values.secretName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  s3-account: {{ .Values.account | b64enc }}
  s3-user: {{ .Values.user | b64enc }}
  s3-password: {{ .Values.password | b64enc }}
  s3-endpoint: {{ .Values.endpoint | b64enc }}
  s3-bucket: {{ .Values.bucketName | b64enc }}
