---
kind: Service
apiVersion: v1
metadata:
  name: gluster-s3-service
  labels:
    gluster-s3: gluster-s3 
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    gluster-s3: gluster-s3 
  type: ClusterIP
  sessionAffinity: None
