---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  labels:
    app: s3-secret
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  s3-account: {{ .Values.account | b64enc }}
  s3-user: {{ .Values.user | b64enc }}
  s3-password: {{ .Values.password | b64enc }}
  {{- if .Values.defaultBucket.enabled }}
  s3-bucket: {{ .Values.defaultBucket.name | b64enc }}
  {{- end }}
