---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: main-gs3-pvc
  annotations:
    volume.alpha.kubernetes.io/storage-class: gluster-heketi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mainPvcRequest }}
