---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvc2Name }}
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc2Request }}
