apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pachd.secretName }}
  labels:
    app: {{ .Values.pachd.secretName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    suite: pachyderm
data:
  minio-id: {{ .Values.glusters3.id | b64enc }}
  minio-secret: {{ .Values.glusters3.key | b64enc }}
  minio-bucket: {{ .Values.glusters3.bucketName | b64enc }}
  minio-endpoint: {{ .Values.glusters3.endpoint | b64enc }}
  minio-secure: {{ .Values.glusters3.secure | b64enc }}
  minio-signature: {{ .Values.glusters3.signature | b64enc }}
