---
credentials: ""

s3:
 accessKey: ""
 secretKey: ""
 bucketName: ""
 endpoint: ""
 secure: "0"
 signature: "0"

google:
 bucketName: ""

amazon:
 bucketName: ""
 distribution: ""
 id: ""
 region: ""
 secret: ""
 token: ""

microsoft:
 container: ""
 id: ""
 secret: ""

pachd:
 secretName: pachyderm-storage-secret
 replicaCount: 1
 volumes:
  volumeName: pachdvol
  secVolName: pachyderm-storage-secret
 resources:
  requests:
   cpu: 1
   memory: 2G
 image:
  repository: pachyderm/pachd
  tag: 1.6.6
  pullPolicy: Always
 worker:
  repository: pachyderm/worker
  tag: 1.6.6

etcd:
 replicaCount: 1
 volumes:
  volumeName: etcdvol
 volumeClaim:
  name: etcdclaim
  # storageClass: <storageClass>
  storage: 20G
  accessModes: ReadWriteMany
 resources:
  requests:
   cpu: 1
   memory: 2G
 image:
  repository: pachyderm/etcd
  tag: v3.2.7
  pullPolicy: IfNotPresent
